### ISSUE TITLE
Wine 퍼포먼스 관련 문의

### ISSUE THREAD

**Issue by ChaseKang** [jeonghanlee/kakaotalk-env#2]
**Describe the bug**
안녕하세요, 먼저 이런 패키지를 만들어 주셔서 정말 감사합니다. 

README.md에 적힌대로 따라 하여 모두 설치를 완료하였는데, 이게 무슨 이유인지 "대화내용을 불러오는 중입다다." 에서 멈추는 현상이 발생하였습니다.

혹시 그런 현상을 겪으셨는지요?

**To Reproduce**
아래 이미지를 참고하시기 바랍니다.
(https://user-images.githubusercontent.com/65214537/89882494-41cda000-dc0a-11ea-904c-5e13bb2b2220.png)

**Expected behavior**
대화내용이 잘 보이는 것을 기대하였습니다!

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Kernel Version
```
Linux -P34V2 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jeonghanlee** [comment]
머신에서는 한글 입력 부분이 창 밖에서 되는 경우 및 그림이 잘 받아 지지않는 이슈 이외엔 메신저를 하는데 있어서는 아무런 문제가 없습니다. 가끔 카카오쪽 서버에 접속이 되지 않을때가 생기지만 두어번 재접속을 하면 문제가 해결되곤 합니다. 

저도 이쪽 분야를 잘몰라, 뭐라고 대답드리기 어렵고,  단지  제가 우분투를 사용하지 않아 시간 나는데로 VM으로 테스트 해보겠습니다. 한가지 제 머리속에 든 생각은 firewall 관련 해서 확인 부탁 드립니다. 그리고 환경이 VM이신지, 직접 인스톨을 하신건지 알려주실 수 있으세요?

**Comment by jeonghanlee** [comment]
Ubuntu 20.04 VM 으로 테스트를 해봤습니다. 제 경우는 문제 없이 메세지를 주고 받을 수 있었습니다. 화면 캡쳐에  https://github.com/jeonghanlee/kakaotalk-env/blob/master/images/ubuntu20.png 주고 받은 메세지를 보실수 있으실껍니다. 

와인 퍼포먼스는 아닌 듯 해 보입니다. 디폴트 ufw를 작동시켜도 카톡 메세지를 주고 받을 수 있었습니다. 아무래도 커스터마이징 된 방화벽 이슈일 듯 합니다. 

제가 해볼 수 있는 부분은 지난 듯 보입니다. 혹 솔루션을 찾으시면 알려주시길 바랍니다.

**Comment by jeonghanlee** [comment]
1주일 후에, 이슈 클로징 하겠습니다. 다른 부분의 이슈가 있으시면, 다시 열어 주시길 바랍니다.

**Comment by ChaseKang** [comment]
안녕하세요. 친절한 답장 감사합니다.

일단 현상을 해결? 하였습니다.  카카오톡 서버 문제였던것 같습니다. 오늘 저녁 다시 카카오톡에 접속하니 정상 작동합니다.

vm이 아닌 직접 인스톨 하였습니다.


저는 아이티 공부한지 한달 밖에 안된 아직 초짜입니다.

이번에도 카카옥톡 설치하면서 많은걸 배웠습니다. ^^

다시 한번 감사드립니다.

2020년 8월 12일 (수) 오전 10:54, Jeong Han Lee <notifications@github.com>님이 작성:

**Comment by jeonghanlee** [comment]
해결이 되어 다행이네요. 도움이 되니 저도 기쁘구요.
