### ISSUE TITLE
2 bugs do not work, how can I help?

### ISSUE THREAD

**Issue by asamountain** [jeonghanlee/kakaotalk-env#3]
**Describe the bug**

1. Image files do not be sent - but when I keep click those 'retry' side button, randomly make it sent. 
2. When the text lines over than the size of text typing blank, Error comes out.

**To Reproduce**

1. In chat, selecting a photo file through 'clip' button
photo sending failed.

2. Ctrl + c & Ctrl + v with more than 5 lines context,
comes out an error then starting reboot.

**Desktop (please complete the following information):**

 Operating System: Ubuntu 20.04.1 LTS
 Kernel: Linux 5.4.0-42-generic

**Comment by jeonghanlee** [comment]
@sj-log 감사합니다. 한글로 쓰셔도 됩니다.  

1. 제가 살펴본 봐로는 100 kB이상의 화일을 전송시 카카오 서버쪽에서 TCP 연결이 reset이 되네요. 100kB이하일 경우는 테스트한 바로는 거의 전송이 되네요.  실제 코드와 로그가 없는 상태에서는 제 실력으로 디버깅을 할 수 없을 것 같습니다.  하지만 주말에 시간이 나면 wine쪽에서 디버깅 로그를 한번 살펴보도록 하겠습니다. 저는 파일 보내기는 사용하지 않고, 단지 친구와 가족들과 채팅할때만 사용을 합니다. 

2. 제 시스템에서는 380 lines 의 텍스트를 복사했을때에도  이상없이 전송되어지는 것을 확인 했습니다. 짧게 생각을 한 봐로는 Gnome쪽 UI이슈가 아닐까 생각해 보기도 하는데, 추측에 불과 합니다. 다른 윈도 메니져를 사용해서 한번 확인 해 보시기 바랍니다. 참고로 저는 Mate와 FVWM환경에서는 문제 없이 작동 되고 있습니다. 

이 repo는 단지 환경 설정만을 위한 곳이라, 카카오톡/Wine 자체의 문제에 대해서는 제가 기술적으로 깊이 관여할 수 도 없고 (실력이 안됩니다.), 도와드릴 수 없다는 점 다시 한번 말씀 드립니다. 하지만 이렇게라도 도움이 되면 좋겠습니다.

**Comment by asamountain** [comment]
답변 감사드립니다.
@jeonghanlee 님 덕분에 이렇게 리눅스에서 편안히 카톡 쓸 수 있다는 점에 진심으로 감사하고 있다는 말씀 먼저 덧붙여드리고 싶네요. 

윈도 매니져, Wine 쪽 디버깅 등, 운영체제와 관련된 부분도 제가 깊지 않아서 뭐라고 답변을 드리기가 애매한 것 같습니다.
운영체제를 더 공부하거나, 시간이 생기거든 저도 한번 들여다볼 수 있을 기회가 있으면 좋겠습니다.

바쁜 와중에도 답변해주셔서 진심으로 감사드립니다.
